#!/bin/bash

LATTE_CONFIG="$HOME/.config/latte/Default.layout.latte"
CURSOR_CONFIG="$HOME/.config/kcminputrc"
SCALING_CONFIG="$HOME/.config/kdeglobals"
FONT_CONFIG="$HOME/.config/kcmfonts"

# Check if $1 has been given
if [ -z ${1+x} ]; then
  echo "Usage: $(basename "$0") [external|laptop]"
  exit 1
fi

if [ "$1" = "external" ]; then
  # Settings for external display
  LATTE_DOCK_SIZE="48"
  LATTE_PANEL_SIZE="18"
  CURSOR_SIZE="24"
  SCALING="1"
  FORCE_FONT_DPI="96"
  SCREEN_SCALE_FACTORS="eDP-1=1;DP-1=1;DP-2=1;"
elif [ "$1" = "laptop" ]; then
  # Settings for laptop (hidpi) display
  LATTE_DOCK_SIZE="86"
  LATTE_PANEL_SIZE="36"
  CURSOR_SIZE="48"
  SCALING="2"
  FORCE_FONT_DPI="192"
  SCREEN_SCALE_FACTORS="eDP-1=2;DP-1=2;DP-2=2;DP-3=2;"
else
  # If $1 is not either 'laptop' or 'external', throw an error
  echo "$1 is not a recognised option"
  echo "Usage: $(basename "$0") [external|laptop]"
  exit 1
fi

# Configure latte dock
kwriteconfig5 --file $LATTE_CONFIG --group "Containments" --group "1" --group "General" --key "iconSize" "$LATTE_DOCK_SIZE"

# Configure latte panel
kwriteconfig5 --file $LATTE_CONFIG --group "Containments" --group "4" --group "General" --key "iconSize" "$LATTE_PANEL_SIZE"

# Configure cursor scaling
kwriteconfig5 --file $CURSOR_CONFIG --group "Mouse" --key "cursorSize" "$CURSOR_SIZE"

# Configure display scaling
kwriteconfig5 --file $SCALING_CONFIG --group "KScreen" --key "ScaleFactor" "$SCALING"
kwriteconfig5 --file $SCALING_CONFIG --group "KScreen" --key "ScreenScaleFactors" "$SCREEN_SCALE_FACTORS"
kwriteconfig5 --file $FONT_CONFIG --group "General" --key "forceFontDPI" "$FORCE_FONT_DPI"

echo "Settings changed, please log out and back in"
