#!/usr/bin/env python3

import os
import argparse
import re

HOME = os.environ['HOME']

paths = {
    'latte_config': HOME + '/.config/latte/Default.layout.latte',
    'cursor_config': HOME + '/.config/kcminputrc',
    'scaling_config': HOME + '/.config/kdeglobals',
    'font_config': HOME + '/.config/kcmfonts',
    'rofi_config': HOME + '/.config/rofi/config.rasi'
}

laptop_settings = {
    # Settings for laptop (hidpi) display
    'latte_panel_size': '64',
    'latte_screen_edge_margin': '16',
    'cursor_size': '48',
    'scaling': '2',
    'force_font_dpi': '192',
    'screen_scale_factors': 'eDP-1=2;DP-1=2;DP-2=2;DP-3=2;',
    'rofi_fontsize': '20'
}

external_settings = {
    # Settings for external display
    'latte_panel_size': '32',
    'latte_screen_edge_margin': '8',
    'cursor_size': '24',
    'scaling': '1',
    'force_font_dpi': '96',
    'screen_scale_factors': 'eDP-1=1;DP-1=1;DP-2=1;',
    'rofi_fontsize': '10'
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("display", help="Define the display to target", choices=[
                        'laptop', 'external'])
    args = parser.parse_args()

    if args.display == 'laptop':
        settings = laptop_settings

    if args.display == 'external':
        settings = external_settings

    apply_kde_config(settings)
    apply_rofi_config(settings)
    print('[+] Settings applied. Please log out and back in if you\'re inside an active session')


def apply_kde_config(settings):
    config = {**paths, **settings}

    try:
        # Configure latte panel
        os.system(
            'kwriteconfig5 --file {latte_config} --group "Containments" --group "1" --group "General" --key "iconSize" "{latte_panel_size}"'.format(**config))
        os.system(
            'kwriteconfig5 --file {latte_config} --group "Containments" --group "1" --group "General" --key "screenEdgeMargin" "{latte_screen_edge_margin}"'.format(**config))

        # Configure cursor scaling
        os.system(
            'kwriteconfig5 --file {cursor_config} --group "Mouse" --key "cursorSize" "{cursor_size}"'.format(**config))

        # Configure display scaling
        os.system(
            'kwriteconfig5 --file {scaling_config} --group "KScreen" --key "ScaleFactor" "{scaling}"'.format(**config))
        os.system(
            'kwriteconfig5 --file {scaling_config} --group "KScreen" --key "ScreenScaleFactors" "{screen_scale_factors}"'.format(**config))
        os.system(
            'kwriteconfig5 --file {font_config} --group "General" --key "forceFontDPI" "{force_font_dpi}"'.format(**config))
    except:
        print('[!] kwriteconfit5 broke. Please investigate.')


def apply_rofi_config(settings):
    # Configure rofi settings
    config = {**paths, **settings}

    try:
        with open(config['rofi_config'], 'r') as f:
            lines = f.readlines()
        with open(config['rofi_config'], 'w') as f:
            for line in lines:
                f.write(re.sub(
                    r'Noto Sans [0-9][0-9]', 'Noto Sans {rofi_fontsize}'.format(**config), line))
    except:
        print('[!] Couldn\'t read or write rofi config. Please investigate.')


if __name__ == "__main__":
    # execute only if run as a script
    main()
