#!/usr/bin/env python3

import os
import argparse
import sys


def check_ext(file):
    extension = os.path.splitext(file)[1][1:]

    if extension == 'md':
        pass
    else:
        return(False)
    return('skip')


def check_present(file):
    return os.path.isfile(file)


def gen_pdf(file):
    filename = os.path.splitext(file)[0]
    os.system('pandoc -o {}.pdf {} --pdf-engine xelatex'.format(filename, file))


def gen_docx(file):
    filename = os.path.splitext(file)[0]
    os.system('pandoc -o {}.docx {}'.format(filename, file))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'file', help='name of the markdown file to use')
    parser.add_argument('--docx', action='store_true',
                        help='also generate a docx file')
    args = parser.parse_args()

    if not check_ext(args.file):
        print('File {} is not a markdown file'.format(args.file))
        sys.exit(1)
    if not check_present(args.file):
        print('Couldn\'t find {}'.format(args.file))
        sys.exit(1)

    gen_pdf(args.file)

    if args.docx:
        gen_docx(args.file)


if __name__ == "__main__":
    # execute only if run as a script
    main()
